# Generated by Django 4.2.12 on 2024-07-31 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_customuser_username"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="username",
        ),
    ]
