# Generated by Django 4.2.12 on 2024-07-31 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_remove_customuser_username"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="customuser",
            managers=[],
        ),
    ]
