# Generated by Django 5.0.6 on 2024-07-01 16:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inbox", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="sentmessage",
            name="sent_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddConstraint(
            model_name="sentmessage",
            constraint=models.CheckConstraint(
                check=models.Q(("sent_by__isnull", False)), name="sentby_cantbe_null"
            ),
        ),
    ]
