# Generated by Django 4.2.12 on 2024-08-05 21:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("inbox", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipient",
            name="contact_owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contact_owner",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
