# Generated by Django 4.2.12 on 2024-08-05 22:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("inbox", "0003_recipient_contact_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="messagetemplate",
            name="message_owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="message_owner",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
