# Generated by Django 4.2.12 on 2024-08-07 13:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("inbox", "0004_messagetemplate_message_owner"),
    ]

    operations = [
        migrations.RenameField(
            model_name="messagetemplate",
            old_name="message",
            new_name="content",
        ),
        migrations.AddField(
            model_name="group",
            name="group_owner",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="group_owner",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="messagetemplate",
            name="description",
            field=models.CharField(default=0, max_length=1024),
            preserve_default=False,
        ),
    ]
