# Generated by Django 4.2.12 on 2024-09-02 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inbox", "0006_alter_group_recipients"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sentmessage",
            name="groups",
        ),
        migrations.RemoveField(
            model_name="sentmessage",
            name="recipients",
        ),
        migrations.AddField(
            model_name="sentmessage",
            name="groups",
            field=models.CharField(default=0, max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="sentmessage",
            name="recipients",
            field=models.CharField(default=0, max_length=2000),
            preserve_default=False,
        ),
    ]
